Document comparing MQTT client libraries in Rust.
dwhiteddsoft/viper-hold pull request #20
Opened 2021-04-06 00:05 UTC by toddpenland

This PR is for [story 86](https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/86).

2021-04-06 11:03 UTC, dwhiteddsoft requested changes
In my opinion, I would be a little more direct with the recommendation. This is a partnership between us and the customer. To that end, I would recommend to keep with what IoT Hub supports and leave it at that. State your assumptions in the doc and then pick 3 that run under current support and let's get started. If you write it the way you currently have it, it leaves room for people to delay decisions and stops us until we make them

2021-04-06 11:04 UTC, dwhiteddsoft commented
also, you are going to need to approvers to get through the gate

2021-04-06 18:11 UTC, toddpenland commented
I have made the requested changes.

2021-04-06 19:20 UTC, dwhiteddsoft approved these changes

2021-04-07 15:02 UTC, haroldwongms approved these changes

2021-04-07 15:09 UTC, merged